### ISSUE TITLE
BUG: `nox` crashes if a parameter name collides with a session name

### ISSUE THREAD

**Issue by dhermes** [jonparrott/nox#66]
I would **not** rate this bug as very severe.

```python
import nox


@nox.session
@nox.parametrize('py', ['2.7', '3.5', '3.6'])
def py(session):
    session.virtualenv = False
    session.interpreter = 'python{}'.format(py)
    command = 'import sys; print(sys.executable)'
    session.run('python', '-c', command)
```

results in

```
C:\Users\dhermes>venv\Scripts\nox.exe -s "py(py='2.7')"
nox > Running session py(py='2.7')
Traceback (most recent call last):
  File "C:\Users\dhermes\venv\Scripts\nox-script.py", line 11, in <module>
    load_entry_point('nox-automation==0.18.1', 'console_scripts', 'nox')()
  File "C:\Users\dhermes\venv\lib\site-packages\nox\main.py", line 107, in main
    tasks.final_reduce,
  File "C:\Users\dhermes\venv\lib\site-packages\nox\workflow.py", line 44, in execute
    return_value = function_(*args, global_config=global_config)
  File "C:\Users\dhermes\venv\lib\site-packages\nox\tasks.py", line 175, in run_manifest
    result = session.execute()
  File "C:\Users\dhermes\venv\lib\site-packages\nox\sessions.py", line 296, in execute
    self._create_config()
  File "C:\Users\dhermes\venv\lib\site-packages\nox\sessions.py", line 249, in _create_config
    self.func(self.config)
  File "C:\Users\dhermes\venv\lib\site-packages\nox\_parametrize.py", line 80, in call_wrapper
    return func(*args, **kwargs)
TypeError: py() got an unexpected keyword argument 'py'
```

**Comment by dhermes** [comment]
JK that was PEBKAC. I never add `py` to the argument list. MERP city!
